ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
# Bootloader selection
BOOTLOADER = rp2040
MIDI_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes

SERIAL_DRIVER = vendor

CONVERT_TO = liatris